### ISSUE TITLE
European data missing from blog post 

### ISSUE THREAD

**Issue by Lvulis** [Nowosad/sabre#10]
Hi Jakub,

I am interested in reproducing the blog post you on your [website](https://jakubnowosad.com/posts/2018-09-10-sabre-bp/) have showcasing the `sabre` package and cannot seem to download the European boundary data from the SIL website. The data doesn't seem to be found at the following url - `http://sil.uc.edu/cms/data/uploads/software_data/vmeasure/regions.zip` 
Is there another resource for this zip? 

Thanks,
Lawrence

**Comment by Nowosad** [comment]
Dear @Lvulis -- thank you a lot for letting me know about this issue. I have fixed it -- you can find a new link at https://jakubnowosad.com/posts/2018-09-10-sabre-bp/. Let me know if there are any other problems.
